# Generated by Django 4.2 on 2026-04-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarefa',
            options={'ordering': ['-prioridade', '-criado_em'], 'verbose_name': 'Tarefa', 'verbose_name_plural': 'Tarefas'},
        ),
        migrations.AddField(
            model_name='tarefa',
            name='categoria',
            field=models.CharField(choices=[('estudos', 'Estudos'), ('trabalho', 'Trabalho'), ('pessoal', 'Pessoal'), ('saude', 'Saúde'), ('outros', 'Outros')], default='outros', max_length=20, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Vencimento'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='titulo',
            field=models.CharField(default='', max_length=200, verbose_name='Título'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='prioridade',
            field=models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=10, verbose_name='Prioridade'),
        ),
    ]
