services:
  - type: web
    name: bootcamp2-web
    env: python
    branch: entrega-intermediaria
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    releaseCommand: python manage.py migrate
